id: A4944BBE8
title: 'The Concentration of Blessings: Red Tārā Lineage Prayer'
type: translation
pechas:
- IB0ED46B5
- IF71710CC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:45:43.467598
  last_modified_at: 2023-01-04 11:45:43.467606
  collections:
  - Drikung Tertön Ösel Dorje
  - Works of Tibetan Masters
alignment_to_base:
  IB0ED46B5/E60A: 8BC5
  IF71710CC/BBB6: 8BC5
